/* empty css                      */import{S,i as s,a as L}from"./assets/vendor-D1mpe0f-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function p(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=p(e);fetch(e.href,r)}})();const y=document.querySelector("#search-form"),f=document.querySelector(".gallery"),a=document.querySelector(".loader"),c=document.querySelector(".load-more"),v="56419387-b9216e8761a1aa448b5b4bea2";let d="",n=1;const u=40;let m=new S(".gallery a",{captionsData:"alt",captionDelay:250});y.addEventListener("submit",q);c.addEventListener("click",P);async function q(t){if(t.preventDefault(),d=t.currentTarget.elements.searchQuery.value.trim(),!d){s.warning({message:"Please enter a search term.",position:"topRight"});return}n=1,f.innerHTML="",c.style.display="none",a.style.display="block";try{const o=await g(d,n);if(a.style.display="none",o.hits.length===0){s.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"});return}h(o.hits),m.refresh(),n*u<o.totalHits?c.style.display="block":s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{a.style.display="none",s.error({title:"Error",message:"Something went wrong while fetching data.",position:"topRight"})}y.reset()}async function P(){n+=1,c.style.display="none",a.style.display="block";try{const t=await g(d,n);h(t.hits),m.refresh(),a.style.display="none",R(),n*u>=t.totalHits?s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#0099FF",messageColor:"#fff"}):c.style.display="block"}catch{a.style.display="none",s.error({title:"Error",message:"Something went wrong while fetching data.",position:"topRight"})}}async function g(t,o){return(await L.get("https://pixabay.com/api/",{params:{key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:u}})).data}function h(t){const o=t.map(({webformatURL:p,largeImageURL:i,tags:e,likes:r,views:l,comments:b,downloads:w})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${i}">
        <img class="gallery-image" src="${p}" alt="${e}" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b><span>${r}</span></p>
        <p class="info-item"><b>Views</b><span>${l}</span></p>
        <p class="info-item"><b>Comments</b><span>${b}</span></p>
        <p class="info-item"><b>Downloads</b><span>${w}</span></p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",o)}function R(){const t=document.querySelector(".gallery-item");if(t){const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
